[project]
name = "yojna"
version = "0.1.0"
description = "Recommendation System"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.2",
    "notebook>=7.4.5",
    "pandas>=2.2.2",
    "scikit-learn>=1.5.1",
    "numpy>=2.0.0",
]